/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADemo: typeof import('./src/components/ADemo.vue')['default']
    AmapDemo: typeof import('./src/components/AmapDemo.vue')['default']
    copy: typeof import('./src/components/VwHubMap copy.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LearletMap: typeof import('./src/components/LearletMap.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    Upload: typeof import('./src/components/Upload.vue')['default']
    VwHubMap: typeof import('./src/components/VwHubMap.vue')['default']
    VwHubMapDemo: typeof import('./src/components/VwHubMapDemo.vue')['default']
  }
}
